### ISSUE TITLE
Message from use-route-as-state

### ISSUE THREAD

**Issue by baruchiro** [ei-labo/front#1]
Hi, I'm the owner of the `use-route-as-state` package.

https://github.com/ei-labo/front/blob/1b2cb5ff7f3cab3c9ec65923fe1ab50410662a9c/package.json#L37

If you need any help, bug, or feature, please feel free to open an issue.

https://github.com/baruchiro/use-route-as-state

Good luck!

**Comment by m1kit** [comment]
Hi! I feel it's really nice.
I will report your if I find something. Thank you!!!
